export enum FeatureKey {
  DAILY_TIPS = 'DAILY_TIPS',
  DECIDED_CASES = 'DECIDED_CASES',
  BASIC_SEARCH = 'BASIC_SEARCH',
  ADVANCED_SEARCH = 'ADVANCED_SEARCH',
  TAX_CALCULATOR = 'TAX_CALCULATOR',
  EXPORT_PDF = 'EXPORT_PDF',
}
